#ifndef NSL_LINALG_INCLUDE_HPP
#define NSL_LINALG_INCLUDE_HPP

#include "LinAlg/complex.tpp"
#include "LinAlg/abs.tpp"
#include "LinAlg/adjoint.tpp"
#include "LinAlg/conj.tpp"
#include "LinAlg/ceil.tpp"
#include "LinAlg/diag.tpp"
#include "LinAlg/det.tpp"
#include "LinAlg/transpose.tpp"
#include "LinAlg/exp.tpp"
#include "LinAlg/flip.tpp"
#include "LinAlg/log.tpp"
#include "LinAlg/inner_product.tpp"
#include "LinAlg/mat_exp.tpp"
#include "LinAlg/mat_mul.tpp"
#include "LinAlg/bmm.tpp"
#include "LinAlg/qr.tpp"
#include "LinAlg/svd.tpp"
#include "LinAlg/mat_mul_stab.tpp"
#include "LinAlg/mat_vec.tpp"
#include "LinAlg/minMax.tpp"
#include "LinAlg/shift.tpp"
#include "LinAlg/mat_inv.tpp"
#include "LinAlg/mat_inv_stab.tpp"
#include "LinAlg/eigh.tpp"
#include "LinAlg/eig.tpp"
#include "LinAlg/tensordot.tpp"
#include "LinAlg/sqrt.tpp"
#include "LinAlg/solve.tpp"
#include "LinAlg/einsum.tpp"
#include "LinAlg/chop.tpp"

#include "LinAlg/Solver/Solver.hpp"
// includes CG.hpp
#include "LinAlg/Solver/Impl/CG.tpp" 
#include "LinAlg/Solver/Impl/CGpreconditioned.tpp" 
#include "LinAlg/Solver/Impl/BiCGStab.tpp"

#endif
